import { Budget } from "../../@types/eleventy";

export const BUDGET_2020: Budget[] = [
  {
    year: 2020,
    title: "Moderná prezentácia pamiatok a pamätihodností MČ",
    id: "2020-1",
    program: 1,
    amountOriginal: 0,
    amountUpdated: 0,
    amountReal: 0,
    comment: "niCE life projekt. Náhradné čerpanie za neschválený pôvodný projekt. Pre potreby niCE life projektu sú potrebné iba bežné výdavky. Kapitálové výdavky v roku 2020 nebudú čerpané",
    status: "error",
  },
  {
    year: 2020,
    title: "Nákup licencie software na verejné obstarávanie",
    id: "2020-2",
    program: 2,
    amountOriginal: 3000,
    amountUpdated: 1500,
    amountReal: 0,
    comment: "Príprava podkladov na verejné obstarávanie",
    status: "inwork",
  },
  {
    year: 2020,
    title: "Virtualizácie serverov",
    id: "2020-3",
    program: 2,
    amountOriginal: 30000,
    amountUpdated: 30000,
    amountReal: 0,
    comment: "priebežne sa plní",
    status: "inwork",
  },
  {
    year: 2020,
    title: "Komunikačná infraštruktúra",
    id: "2020-4",
    program: 2,
    amountOriginal: 35000,
    amountUpdated: 30000,
    amountReal: 16253.42,
    comment: "priebežne sa plní",
    status: "inwork",
  },
  {
    year: 2020,
    title: "Rekonštrukcia chodníkov",
    id: "2020-5",
    program: 4,
    amountOriginal: 100000,
    amountUpdated: 95000,
    amountReal: 36836,
    comment: "",
    status: "inwork",
  },
  {
    year: 2020,
    title: "Rekonstrukcia a modernizácia komunikácii",
    id: "2020-6",
    program: 4,
    amountOriginal: 80000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2020,
    title: "Vybudovanie cyklotrasy, prípadne nových chodníkov",
    id: "2020-7",
    program: 4,
    amountOriginal: 145000,
    amountUpdated: 15852,
    amountReal: 5352,
    comment: "platba za PD, aktualne prebiehaju zistovania vlastnickych vztahov na pozemkoch cyklotras",
    status: "inwork",
  },
  {
    year: 2020,
    title: "Prípravná projektová dokumentácia a budovanie nových chodníkov",
    id: "2020-8",
    program: 4,
    amountOriginal: 370000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "Nerealizuje sa, bolo by vhodné od MZ presunúť na opravu jestvujúcich chodnikov",
    status: "error",
  },
  {
    year: 2020,
    title: "Projektová dokumentácia na nové parkoviská",
    id: "2020-9",
    program: 4,
    amountOriginal: 23000,
    amountUpdated: 14437.8,
    amountReal: 14437.8,
    comment: "zrealizované",
    status: "success",
  },
  {
    year: 2020,
    title: "Rekonštrukcia školkských zariadení",
    id: "2020-10",
    program: 5,
    amountOriginal: 911536,
    amountUpdated: 867554.53,
    amountReal: 454520.07,
    comment: "realizuje sa",
    status: "inwork",
  },
  {
    year: 2020,
    title: "Dotácia na obnovu odborných učební ZŠ",
    id: "2020-11",
    program: 5,
    amountOriginal: 777246,
    amountUpdated: 0,
    amountReal: 0,
    comment: "Nenávratný finančný príspevok bol schválený. Dodávateľ je vysúťažený. Zmluvy sú na kontrole na ministerstve. S realizáciou projektu plánujeme začať od roku 2021, nepredpokladáme čerpanie v roku 2020",
    status: "postpone",
  },
  {
    year: 2020,
    title: "Rekonštrukcia časti objektu za účelom zvýšenia kapacity",
    id: "2020-12",
    program: 5,
    amountOriginal: 18740,
    amountUpdated: 0,
    amountReal: 0,
    comment: "Nenávratný finančný príspevok bol schválený. Dodávateľ je vysúťažený. Zmluvy sú na kontrole na ministerstve. S realizáciou projektu plánujeme začať od roku 2021, nepredpokladáme čerpanie v roku 2020",
    status: "postpone",
  },
  {
    year: 2020,
    title: "Rekonštrukcia a vybavenie odborných učební",
    id: "2020-13",
    program: 5,
    amountOriginal: 94734,
    amountUpdated: 0,
    amountReal: 0,
    comment: "Nenávratný finančný príspevok bol schválený. Dodávateľ je vysúťažený. Zmluvy sú na kontrole na ministerstve. S realizáciou projektu plánujeme začať od roku 2021, nepredpokladáme čerpanie v roku 2020",
    status: "postpone",
  },
  {
    year: 2020,
    title: "Vybudovanie klimatizácie v DK Zrkadlový háj",
    id: "2020-14",
    program: 6,
    amountOriginal: 0,
    amountUpdated: 0,
    amountReal: 0,
    comment: "Spracováva sa projektová dokumentácia v réžii KZP",
    status: "error",
  },
  {
    year: 2020,
    title: "Rekonštrukcia jestvujúceho multifunkčného ihriska",
    id: "2020-15",
    program: 6,
    amountOriginal: 0,
    amountUpdated: 0,
    amountReal: 0,
    comment: "Zrealizované cez bežné výdavky",
    status: "success",
  },
  {
    year: 2020,
    title: "Revitalizácia športového areálu,  multifunkčného ihriska - I. fáza",
    id: "2020-16",
    program: 6,
    amountOriginal: 67123,
    amountUpdated: 30000,
    amountReal: 0,
    comment: "Realizovať sa bude projektová dokumentácia na multifunkčné ihrisko a dráhu. Prebieha príprava súťaže.",
    status: "inwork",
  },
  {
    year: 2020,
    title: "Výmena mantinelov",
    id: "2020-17",
    program: 6,
    amountOriginal: 0,
    amountUpdated: 18534,
    amountReal: 18534,
    comment: "Realizácia v polovici 10/2020",
    status: "success",
  },
  {
    year: 2020,
    title: "Nákup vozidiel a plošiny (žacích strojov s príslušenstvom)",
    id: "2020-18",
    program: 7,
    amountOriginal: 219348,
    amountUpdated: 179348,
    amountReal: 113075.99,
    comment: "",
    status: "inwork",
  },
  {
    year: 2020,
    title: "Vybudovanie jedného nového výbehu pre psov",
    id: "2020-19",
    program: 7,
    amountOriginal: 0,
    amountUpdated: 0,
    amountReal: 0,
    comment: "Prebieha identifikácia vhodných pozemkov. V roku 2020 sa nebude realizovať",
    status: "postpone",
  },
  {
    year: 2020,
    title: "Príspevky na stavebné úpravy a vybudovanie nových kontajnerových stanovíšť",
    id: "2020-20",
    program: 7,
    amountOriginal: 10000,
    amountUpdated: 10000,
    amountReal: 0,
    comment: "Priebežne sa plní",
    status: "inwork",
  },
  {
    year: 2020,
    title: "Revitalizácia verejných detských ihrísk (príslušenstvo k strojom, prístrojom, zariadeniam a technikám)",
    id: "2020-21",
    program: 7,
    amountOriginal: 63200,
    amountUpdated: 53322,
    amountReal: 38322,
    comment: "Prebieha inventarizácia stavu detských ihrísk",
    status: "inwork",
  },
  {
    year: 2020,
    title: "Nákup nákladných automobilov a prevádzkových strojov a prístrojov (2 kusov nákladných automobilov značky Man, jadrovej vŕtačky a stolového sústruhu)",
    id: "2020-22",
    program: 7,
    amountOriginal: 91614,
    amountUpdated: 89384.33,
    amountReal: 89384.33,
    comment: "",
    status: "success",
  },
  {
    year: 2020,
    title: "Dofinancovanie ÚP zóny Kapitulský dvor",
    id: "2020-23",
    program: 8,
    amountOriginal: 34757,
    amountUpdated: 34757,
    amountReal: 34757,
    comment: "V procese spracovania návrhu ÚP",
    status: "success",
  },
  {
    year: 2020,
    title: "Vybudovanie denného stacionáru",
    id: "2020-24",
    program: 9,
    amountOriginal: 34651,
    amountUpdated: 0,
    amountReal: 0,
    comment: "Nenávratný finančný prispevok bol zamietnutý. Aktuálne prebieha odvolacie konanie",
    status: "postpone",
  },
  {
    year: 2020,
    title: "Participatívny výskum na Nám. Republiky a Šrobárovom námestí",
    id: "2020-25",
    program: 9,
    amountOriginal: 34730,
    amountUpdated: 23570,
    amountReal: 8200,
    comment: "",
    status: "inwork",
  },
  {
    year: 2020,
    title: "Riešenie sociálneho zariadenia pre seniorov, prípadne na zvýšenie kapacity MŠ",
    id: "2020-26",
    program: 9,
    amountOriginal: 0,
    amountUpdated: 0,
    amountReal: 0,
    comment: "Prebratie objektu Hrobákova, na obhliadke objektu Hrobáková sa určila cena rekonštrukcie ref, investičných činností na sumu 450 000 - 520 000 €",
    status: "inwork",
  },
  {
    year: 2020,
    title: "Nákup budov, objektov a ich časti",
    id: "2020-27",
    program: 9,
    amountOriginal: 15100,
    amountUpdated: 15100,
    amountReal: 15100,
    comment: "Zrealizované",
    status: "success",
  },
  {
    year: 2020,
    title: "Vyhotovenie projektových dokumentácií k novým projektom podľa vyhlásených výziev",
    id: "2020-28",
    program: 9,
    amountOriginal: 29000,
    amountUpdated: 2065,
    amountReal: 0,
    comment: "Neočakáva sa ďalšie čerpanie",
    status: "success",
  },
  {
    year: 2020,
    title: "Zabezpečenie klimatizácie do ZSS na Vavilovovej ulici",
    id: "2020-29",
    program: 10,
    amountOriginal: 0,
    amountUpdated: 0,
    amountReal: 0,
    comment: "Z dôvodu pandémie nebolo možné realizovať. 26/07/2020 požiadalo ZSS o dotáciu pre zabezpečenie klimatizázie vo vlastnej réžii",
    status: "error",
  },
  {
    year: 2020,
    title: "Obstaranie špeciálneho vozidla pre DVPZ Petržalka",
    id: "2020-30",
    program: 11,
    amountOriginal: 20000,
    amountUpdated: 20000,
    amountReal: 0,
    comment: "V príprave",
    status: "inwork",
  },
  {
    year: 2020,
    title: "Nákup telekomunikačnej techniky - kamery",
    id: "2020-31",
    program: 11,
    amountOriginal: 100000,
    amountUpdated: 100000,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
];

export const BUDGET_2021: Budget[] = [
  {
    year: 2021,
    title: "Poslanecké priority na kapitálové výdavky (rekonštrukcie školských budov, obnova chodníkov a športova infraštruktúra)",
    id: "2021-1",
    program: 1,
    amountOriginal: 205000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Nákup licencie sofware na verejné obstarávanie",
    id: "2021-2",
    previous: "2020-2",
    program: 2,
    amountOriginal: 3000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Obstaranie virtualizácie serverov",
    id: "2021-3",
    previous: "2020-3",
    program: 2,
    amountOriginal: 30000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Obnova komunikácií",
    id: "2021-4",
    previous: "2020-4",
    program: 4,
    amountOriginal: 200000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Cyklotrasa O4 I. Etapa - Prístavného mostu, Májová ulica, Nám. Hraničiarov ",
    id: "2021-5",
    previous: "2020-7",
    program: 4,
    amountOriginal: 185000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Cyklotrasa O4 II. Etapa - Chorvátske rameno po Rusovskú 72 100",
    id: "2021-6",
    previous: "2020-7",
    program: 4,
    amountOriginal: 75000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Bleskozvod na MŠ",
    id: "2021-7",
    program: 5,
    amountOriginal: 32000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Rekonštrukcie ZŠ a MŠ",
    id: "2021-8",
    previous: "2020-10",
    program: 5,
    amountOriginal: 1676980,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Zvýšenie kapacít MŠ",
    id: "2021-9",
    previous: "2020-10",
    program: 5,
    amountOriginal: 891074,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Rekonštrukcia pobočky Vavilovova - PD",
    id: "2021-10",
    program: 6,
    amountOriginal: 25000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Zateplenie DK Zrkadlový háj",
    id: "2021-11",
    program: 6,
    amountOriginal: 210000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Nová bežecká dráha a multifinkčné ihrisko na ZŠ Lachova",
    id: "2021-12",
    previous: "2020-16",
    program: 6,
    amountOriginal: 215000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Nákup strojov a zariadení - podľa potrieb referátu",
    id: "2021-13",
    previous: "2020-18",
    program: 7,
    amountOriginal: 365000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Nákup strojov a zariadení - nákladné vozidlo",
    id: "2021-14",
    previous: "2020-18",
    program: 7,
    amountOriginal: 30000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Revitalizácia detských ihríska",
    id: "2021-15",
    previous: "2020-21",
    program: 7,
    amountOriginal: 121000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "6 verejných detských ihrísk určených na revitalizáciu v roku 2021 bude vybraných na základe výstupov stretnutia poslaneckej pracovnej skupiny začiatkom decembra 2020 - zo stretnutia bude vyhotovená zápisnica",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Nové detské ihrisko na ulici Pečnianska",
    id: "2021-16",
    previous: "2020-21",
    program: 7,
    amountOriginal: 29000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Dotváranie a budovanie kontajnerových stanovíšť",
    id: "2021-17",
    previous: "2020-20",
    program: 7,
    amountOriginal: 10000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "PD Mlynarovičová",
    id: "2021-18",
    program: 7,
    amountOriginal: 10000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "ÚP zóny Kapitulský dvor",
    id: "2021-19",
    program: 8,
    amountOriginal: 7239,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Súťaž návrhov revitalizácie nám. Republiky",
    id: "2021-20",
    previous: "2020-25",
    program: 8,
    amountOriginal: 65000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Vypracovanie PD - MŠ Hrobákova",
    id: "2021-21",
    previous: "2020-26",
    program: 9,
    amountOriginal: 70000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Revitalizácia - Šrobárovo námestie",
    id: "2021-22",
    previous: "2020-25",
    program: 9,
    amountOriginal: 196000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Nákup budov ZSE",
    id: "2021-23",
    program: 9,
    amountOriginal: 1350000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Vypracovanie projektovej dokumnetácie - DSS OSUSKÉHO",
    id: "2021-24",
    program: 9,
    amountOriginal: 70000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Zabezpečenie klimatizácie do ZSS na Vavilovovej ulici",
    id: "2021-25",
    previous: "2020-29",
    program: 10,
    amountOriginal: 14000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
  {
    year: 2021,
    title: "Kamerový systém",
    id: "2021-26",
    program: 11,
    amountOriginal: 100000,
    amountUpdated: 0,
    amountReal: 0,
    comment: "",
    status: "inwork",
  },
];
