spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/world?autoreconnect=true&serverTimezone=UTC&useLegacyDatetimeCode=false"
    username: "root"
    password: "root"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
  jpa:
    properties:
      hibernate:
        generate_statistics: true
logging:
  level:
    root: INFO
    org.hibernate.SQL: debug